services:
  - type: web
    name: user-management-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://kakkuluruchakradhargoud_db_user:VbYzGtmoMESDWqwx@cluster0.mpv48xf.mongodb.net/user-management?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
      - key: FRONTEND_URL
        value: https://usermanagementsystem-red.vercel.app
